repository: cyclr/docs

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Cyclr Documentation
# this appears on the top navigation bar next to the home button

site_title: Cyclr Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Cyclr
# this appears in the footer

github_editme_path: cyclr/docs/blob/master/
# github_editme_path: cyclr/docs/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: 
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

google_analytics: UA-67609083-1
# if you have google-ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .vs/
  - .idea/
  - .gitignore
  - pages/v1/

# these are the files and directories that jekyll will exclude from the build

incremental: false
# incremental build (experimental)

feedback_subject_line: Cyclr documentation

feedback_email: daniel@cyclr.com
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
    comments: true
    search: true
    sidebar: cyclr_sidebar
    topnav: topnav
    show_editme_path: false
    show_tags: false
    show_disqus: false
    default_header: true
    toc: true
    poll: false
    categorylayout: "category_default"
# these are defaults used for the frontmatter for these file types

sidebars:
  - cyclr_sidebar

sass:
  style: compressed

# _config.yml
toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  toc_class: toc_list
  sublist_class: toc_sublist

description: "Documentation for Cyclr."
# the description is used in the feed.xml file


plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
#  - jekyll-menus

# plugin to add metadata tags for search engines and social networks to better index and display site's content

# needed for sitemap.xml file only
# url: https://docs.cyclr.com
# dev build - override baseurl required for github pages?
# prod build: confirm baseurl requirement 
# local build: override the baseurl if required, eg bundle exec jekyll serve --livereload --baseurl="/"

# algolia search debug
search_debug: false

# algolia 
# doc: https://community.algolia.com/jekyll-algolia/getting-started.html
# run the indexing
# ALGOLIA_API_KEY='your_admin_api_key' bundle exec jekyll algolia
algolia:
  application_id: 5267EP9OE1
  index_name: documentation_v2
  files_to_exclude: []
  nodes_to_index: 'p,h2,h3,h4'
  search_only_api_key: a0c27aa7840e0631eee62783163e48dd


